services:
  flow_matching:
    build: .
    image: flow-matching-data-assimilation:latest
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - CLEARML_API_ACCESS_KEY=${CLEARML_API_ACCESS_KEY:-}
      - CLEARML_API_SECRET_KEY=${CLEARML_API_SECRET_KEY:-}
      - CLEARML_API_HOST=${CLEARML_API_HOST:-}
      - CLEARML_WEB_HOST=${CLEARML_WEB_HOST:-}
      - CLEARML_FILES_HOST=${CLEARML_FILES_HOST:-}
      - WANDB_SILENT=true
    volumes:
      - "${DATA_ROOT:-/mnt}:/mnt:ro"
      - "./:/home"
    shm_size: '48gb'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['${GPU_DEVICE_ID:-0}']
            capabilities: [gpu]
