services:
  diffusion_data_assimilation:
    build: .
    image: ${USER}/diffusion_data_assimilation
    container_name: ${USER}_diffusion_data_assimilation
    env_file:
      - .env
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - CLEARML_API_ACCESS_KEY=${CLEARML_API_ACCESS_KEY:-}
      - CLEARML_API_SECRET_KEY=${CLEARML_API_SECRET_KEY:-}
      - CLEARML_API_HOST=${CLEARML_API_HOST:-}
      - CLEARML_WEB_HOST=${CLEARML_WEB_HOST:-}
      - CLEARML_FILES_HOST=${CLEARML_FILES_HOST:-}
      - WANDB_SILENT=true 
    volumes:
      - "/mnt:/mnt"
      - "./:/home/"
    cpuset: 241-255
    shm_size: '48gb'
    deploy: 
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
        limits:
          cpus: '6.0'
          memory: 64G
